name: 'CI-terraform-production-build'

on:
  push:
    branches: [main]

jobs:
  terraform-production-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'main'
        fetch-depth: '1'
    - name: 'Print dependencies'
      run: |
        ./ci-print-dependencies.sh
    - name: 'CI terraform init plan apply Command'
      timeout-minutes: 20
      env:
        ENV_NAME: 'production'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYIDPROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESSKEYPROD }}
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_DEFAULT_OUTPUT: 'json'
      run: |
        ./ci-deployment.sh
