name: 'CI-terraform-destroy-aws'

on:
    push:
      branches: [destroy]
  
jobs:
  terraform-destroy-aws:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'main'
        fetch-depth: '1'a
    - name: 'Print dependencies'
      run: |
        ./ci-print-dependencies.sh
    - name: 'CI terraform destroy Command'
      timeout-minutes: 20
      env:
        ENV_NAME: 'production'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYIDPROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESSKEYPROD }}
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_DEFAULT_OUTPUT: 'json'
      run: |
        ./ci-terraform-destroy.sh
